"""
schedule.py — the full 104-match 2026 World Cup schedule, transcribed from the
official FIFA / Fox Sports schedule. Times are local US Eastern (UTC-4) as given
in the source. Group-stage entries have real teams; knockout entries show the
slot placeholders (e.g. "Win C v 2nd F") since opponents aren't known yet.

Each entry: (date, time_et, stage, group_or_match, matchup, venue)
"""

GROUP_STAGE = [
    ("Thu 11 Jun", "3:00pm", "A", "Mexico v South Africa", "Mexico City"),
    ("Thu 11 Jun", "10:00pm", "A", "South Korea v Czechia", "Guadalajara"),
    ("Fri 12 Jun", "3:00pm", "B", "Canada v Bosnia & Herz.", "Toronto"),
    ("Fri 12 Jun", "9:00pm", "D", "USA v Paraguay", "Los Angeles"),
    ("Sat 13 Jun", "3:00pm", "B", "Qatar v Switzerland", "San Francisco"),
    ("Sat 13 Jun", "6:00pm", "C", "Brazil v Morocco", "New York/NJ"),
    ("Sat 13 Jun", "9:00pm", "C", "Haiti v Scotland", "Boston"),
    ("Sun 14 Jun", "12:00am", "D", "Australia v Turkiye", "Vancouver"),
    ("Sun 14 Jun", "1:00pm", "E", "Germany v Curacao", "Houston"),
    ("Sun 14 Jun", "4:00pm", "F", "Netherlands v Japan", "Dallas"),
    ("Sun 14 Jun", "7:00pm", "E", "Ivory Coast v Ecuador", "Philadelphia"),
    ("Sun 14 Jun", "10:00pm", "F", "Sweden v Tunisia", "Monterrey"),
    ("Mon 15 Jun", "12:00pm", "H", "Spain v Cape Verde", "Atlanta"),
    ("Mon 15 Jun", "3:00pm", "G", "Belgium v Egypt", "Seattle"),
    ("Mon 15 Jun", "6:00pm", "H", "Saudi Arabia v Uruguay", "Miami"),
    ("Mon 15 Jun", "9:00pm", "G", "Iran v New Zealand", "Los Angeles"),
    ("Tue 16 Jun", "3:00pm", "I", "France v Senegal", "New York/NJ"),
    ("Tue 16 Jun", "6:00pm", "I", "Iraq v Norway", "Boston"),
    ("Tue 16 Jun", "9:00pm", "J", "Argentina v Algeria", "Kansas City"),
    ("Wed 17 Jun", "12:00am", "J", "Austria v Jordan", "San Francisco"),
    ("Wed 17 Jun", "1:00pm", "K", "Portugal v Congo DR", "Houston"),
    ("Wed 17 Jun", "4:00pm", "L", "England v Croatia", "Dallas"),
    ("Wed 17 Jun", "7:00pm", "L", "Ghana v Panama", "Toronto"),
    ("Wed 17 Jun", "10:00pm", "K", "Uzbekistan v Colombia", "Mexico City"),
    ("Thu 18 Jun", "12:00pm", "A", "Czechia v South Africa", "Atlanta"),
    ("Thu 18 Jun", "3:00pm", "B", "Switzerland v Bosnia", "Los Angeles"),
    ("Thu 18 Jun", "6:00pm", "B", "Canada v Qatar", "Vancouver"),
    ("Thu 18 Jun", "9:00pm", "A", "Mexico v South Korea", "Guadalajara"),
    ("Fri 19 Jun", "3:00pm", "D", "USA v Australia", "Seattle"),
    ("Fri 19 Jun", "6:00pm", "C", "Scotland v Morocco", "Boston"),
    ("Fri 19 Jun", "8:30pm", "C", "Brazil v Haiti", "Philadelphia"),
    ("Fri 19 Jun", "11:00pm", "D", "Turkiye v Paraguay", "San Francisco"),
    ("Sat 20 Jun", "1:00pm", "F", "Netherlands v Sweden", "Houston"),
    ("Sat 20 Jun", "4:00pm", "E", "Germany v Ivory Coast", "Toronto"),
    ("Sat 20 Jun", "8:00pm", "E", "Ecuador v Curacao", "Kansas City"),
    ("Sun 21 Jun", "12:00am", "F", "Tunisia v Japan", "Monterrey"),
    ("Sun 21 Jun", "12:00pm", "H", "Spain v Saudi Arabia", "Atlanta"),
    ("Sun 21 Jun", "3:00pm", "G", "Belgium v Iran", "Los Angeles"),
    ("Sun 21 Jun", "6:00pm", "H", "Uruguay v Cape Verde", "Miami"),
    ("Sun 21 Jun", "9:00pm", "G", "New Zealand v Egypt", "Vancouver"),
    ("Mon 22 Jun", "1:00pm", "J", "Argentina v Austria", "Dallas"),
    ("Mon 22 Jun", "5:00pm", "I", "France v Iraq", "Philadelphia"),
    ("Mon 22 Jun", "8:00pm", "I", "Norway v Senegal", "New York/NJ"),
    ("Mon 22 Jun", "11:00pm", "J", "Jordan v Algeria", "San Francisco"),
    ("Tue 23 Jun", "1:00pm", "K", "Portugal v Uzbekistan", "Houston"),
    ("Tue 23 Jun", "4:00pm", "L", "England v Ghana", "Boston"),
    ("Tue 23 Jun", "7:00pm", "L", "Panama v Croatia", "Toronto"),
    ("Tue 23 Jun", "10:00pm", "K", "Colombia v Congo DR", "Guadalajara"),
    ("Wed 24 Jun", "3:00pm", "B", "Switzerland v Canada", "Vancouver"),
    ("Wed 24 Jun", "3:00pm", "B", "Bosnia v Qatar", "Seattle"),
    ("Wed 24 Jun", "6:00pm", "C", "Scotland v Brazil", "Miami"),
    ("Wed 24 Jun", "6:00pm", "C", "Morocco v Haiti", "Atlanta"),
    ("Wed 24 Jun", "9:00pm", "A", "Czechia v Mexico", "Mexico City"),
    ("Wed 24 Jun", "9:00pm", "A", "South Africa v South Korea", "Monterrey"),
    ("Thu 25 Jun", "4:00pm", "E", "Curacao v Ivory Coast", "Philadelphia"),
    ("Thu 25 Jun", "4:00pm", "E", "Ecuador v Germany", "New York/NJ"),
    ("Thu 25 Jun", "7:00pm", "F", "Japan v Sweden", "Dallas"),
    ("Thu 25 Jun", "7:00pm", "F", "Tunisia v Netherlands", "Kansas City"),
    ("Thu 25 Jun", "10:00pm", "D", "Turkiye v USA", "Los Angeles"),
    ("Thu 25 Jun", "10:00pm", "D", "Paraguay v Australia", "San Francisco"),
    ("Fri 26 Jun", "3:00pm", "I", "Norway v France", "Boston"),
    ("Fri 26 Jun", "3:00pm", "I", "Senegal v Iraq", "Toronto"),
    ("Fri 26 Jun", "8:00pm", "H", "Cape Verde v Saudi Arabia", "Houston"),
    ("Fri 26 Jun", "8:00pm", "H", "Uruguay v Spain", "Guadalajara"),
    ("Fri 26 Jun", "11:00pm", "G", "Egypt v Iran", "Seattle"),
    ("Fri 26 Jun", "11:00pm", "G", "New Zealand v Belgium", "Vancouver"),
    ("Sat 27 Jun", "5:00pm", "L", "Panama v England", "New York/NJ"),
    ("Sat 27 Jun", "5:00pm", "L", "Croatia v Ghana", "Philadelphia"),
    ("Sat 27 Jun", "7:30pm", "K", "Colombia v Portugal", "Miami"),
    ("Sat 27 Jun", "7:30pm", "K", "Congo DR v Uzbekistan", "Atlanta"),
    ("Sat 27 Jun", "10:00pm", "J", "Jordan v Argentina", "Dallas"),
    ("Sat 27 Jun", "10:00pm", "J", "Algeria v Austria", "Kansas City"),
]

KNOCKOUTS = [
    ("Sun 28 Jun", "3:00pm", "R32 M73", "2nd A v 2nd B", "Los Angeles"),
    ("Mon 29 Jun", "1:00pm", "R32 M76", "Win C v 2nd F", "Houston"),
    ("Mon 29 Jun", "4:30pm", "R32 M74", "Win E v 3rd A/B/C/D/F", "Boston"),
    ("Mon 29 Jun", "9:00pm", "R32 M75", "Win F v 2nd C", "Monterrey"),
    ("Tue 30 Jun", "1:00pm", "R32 M78", "2nd E v 2nd I", "Dallas"),
    ("Tue 30 Jun", "5:00pm", "R32 M77", "Win I v 3rd C/D/F/G/H", "New York/NJ"),
    ("Tue 30 Jun", "9:00pm", "R32 M79", "Win A v 3rd C/E/F/H/I", "Mexico City"),
    ("Wed 1 Jul", "12:00pm", "R32 M80", "Win L v 3rd E/H/I/J/K", "Atlanta"),
    ("Wed 1 Jul", "4:00pm", "R32 M82", "Win G v 3rd A/E/H/I/J", "Seattle"),
    ("Wed 1 Jul", "8:00pm", "R32 M81", "Win D v 3rd B/E/F/I/J", "San Francisco"),
    ("Thu 2 Jul", "3:00pm", "R32 M84", "Win H v 2nd J", "Los Angeles"),
    ("Thu 2 Jul", "7:00pm", "R32 M83", "2nd K v 2nd L", "Toronto"),
    ("Thu 2 Jul", "11:00pm", "R32 M85", "Win B v 3rd E/F/G/I/J", "Vancouver"),
    ("Fri 3 Jul", "2:00pm", "R32 M88", "2nd D v 2nd G", "Dallas"),
    ("Fri 3 Jul", "6:00pm", "R32 M86", "Win J v 2nd H", "Miami"),
    ("Fri 3 Jul", "9:30pm", "R32 M87", "Win K v 3rd D/E/I/J/L", "Kansas City"),
    ("Sat 4 Jul", "1:00pm", "R16 M89", "Win M74 v Win M77", "Philadelphia"),
    ("Sat 4 Jul", "5:00pm", "R16 M90", "Win M73 v Win M75", "Houston"),
    ("Sun 5 Jul", "4:00pm", "R16 M91", "Win M76 v Win M78", "New York/NJ"),
    ("Sun 5 Jul", "8:00pm", "R16 M92", "Win M79 v Win M80", "Mexico City"),
    ("Mon 6 Jul", "3:00pm", "R16 M93", "Win M83 v Win M84", "Dallas"),
    ("Mon 6 Jul", "8:00pm", "R16 M94", "Win M81 v Win M82", "Seattle"),
    ("Tue 7 Jul", "12:00pm", "R16 M95", "Win M86 v Win M88", "Atlanta"),
    ("Tue 7 Jul", "4:00pm", "R16 M96", "Win M85 v Win M87", "Vancouver"),
    ("Thu 9 Jul", "4:00pm", "QF M97", "Win M89 v Win M90", "Boston"),
    ("Fri 10 Jul", "3:00pm", "QF M98", "Win M93 v Win M94", "Los Angeles"),
    ("Sat 11 Jul", "5:00pm", "QF M99", "Win M91 v Win M92", "Miami"),
    ("Sat 11 Jul", "9:00pm", "QF M100", "Win M95 v Win M96", "Kansas City"),
    ("Tue 14 Jul", "3:00pm", "SF M101", "Win M97 v Win M98", "Dallas"),
    ("Wed 15 Jul", "3:00pm", "SF M102", "Win M99 v Win M100", "Atlanta"),
    ("Sat 18 Jul", "5:00pm", "3rd M103", "Loss M101 v Loss M102", "Miami"),
    ("Sun 19 Jul", "3:00pm", "FINAL M104", "Win M101 v Win M102", "New York/NJ"),
]
